/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app.tsx',
    './App.tsx',
  ],
  theme: {
    extend: {
      /* ==========================================================================
         COLORS - Using design system tokens
         ========================================================================== */
      colors: {
        // Primary Colors
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        // Secondary Colors
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        // Semantic Colors
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          950: 'var(--color-success-950)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          950: 'var(--color-warning-950)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          950: 'var(--color-error-950)',
        },
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
          950: 'var(--color-info-950)',
        },
        // Neutral Colors
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        // Legacy color names for backward compatibility
        gray: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        // Special UI colors
        glass: {
          light: 'var(--color-glass-light)',
          medium: 'var(--color-glass-medium)',
          heavy: 'var(--color-glass-heavy)',
        },
        // White and black
        white: 'var(--color-white)',
        black: 'var(--color-black)',
      },

      /* ==========================================================================
         TYPOGRAPHY - Using design system tokens
         ========================================================================== */
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
        '8xl': 'var(--font-size-8xl)',
        '9xl': 'var(--font-size-9xl)',
      },
      fontFamily: {
        primary: 'var(--font-family-primary)',
        mono: 'var(--font-family-mono)',
        display: 'var(--font-family-display)',
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      lineHeight: {
        tight: 'var(--line-height-tight)',
        snug: 'var(--line-height-snug)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose: 'var(--line-height-loose)',
      },
      letterSpacing: {
        tighter: 'var(--letter-spacing-tighter)',
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        wider: 'var(--letter-spacing-wider)',
        widest: 'var(--letter-spacing-widest)',
      },

      /* ==========================================================================
         SPACING - Using design system tokens
         ========================================================================== */
      spacing: {
        px: 'var(--space-px)',
        0: 'var(--space-0)',
        0.5: 'var(--space-0-5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1-5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2-5)',
        3: 'var(--space-3)',
        3.5: 'var(--space-3-5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        13: 'var(--space-13)',
        14: 'var(--space-14)',
        15: 'var(--space-15)',
        16: 'var(--space-16)',
        18: 'var(--space-18)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        28: 'var(--space-28)',
        32: 'var(--space-32)',
        36: 'var(--space-36)',
        40: 'var(--space-40)',
        44: 'var(--space-44)',
        48: 'var(--space-48)',
        52: 'var(--space-52)',
        56: 'var(--space-56)',
        60: 'var(--space-60)',
        64: 'var(--space-64)',
        72: 'var(--space-72)',
        80: 'var(--space-80)',
        96: 'var(--space-96)',
      },

      /* ==========================================================================
         BORDER RADIUS - Using design system tokens
         ========================================================================== */
      borderRadius: {
        xs: 'var(--input-radius-xs)',
        sm: 'var(--input-radius-sm)',
        md: 'var(--input-radius-md)',
        lg: 'var(--input-radius-lg)',
        widget: 'var(--card-radius-lg)',
        'widget-sm': 'var(--card-radius-md)',
        'widget-lg': 'var(--card-radius-xl)',
      },

      /* ==========================================================================
         BOX SHADOWS - Using design system tokens
         ========================================================================== */
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        // Cyberpunk shadows
        'glow-primary-xs': 'var(--shadow-glow-primary-xs)',
        'glow-primary-sm': 'var(--shadow-glow-primary-sm)',
        'glow-primary-md': 'var(--shadow-glow-primary-md)',
        'glow-primary-lg': 'var(--shadow-glow-primary-lg)',
        'glow-secondary-xs': 'var(--shadow-glow-secondary-xs)',
        'glow-secondary-sm': 'var(--shadow-glow-secondary-sm)',
        'glow-secondary-md': 'var(--shadow-glow-secondary-md)',
        'glow-secondary-lg': 'var(--shadow-glow-secondary-lg)',
        'glow-accent-xs': 'var(--shadow-glow-accent-xs)',
        'glow-accent-sm': 'var(--shadow-glow-accent-sm)',
        'glow-accent-md': 'var(--shadow-glow-accent-md)',
        'glow-accent-lg': 'var(--shadow-glow-accent-lg)',
        // Component shadows
        card: 'var(--shadow-card)',
        button: 'var(--shadow-button)',
        modal: 'var(--shadow-modal)',
        tooltip: 'var(--shadow-tooltip)',
        // Special effects
        glass: 'var(--shadow-glass)',
        'cyber-card': 'var(--shadow-cyber-card)',
        interactive: 'var(--shadow-interactive)',
        floating: 'var(--shadow-floating)',
        // Legacy shadows for backward compatibility
        'glow-magenta': 'var(--shadow-glow-secondary-sm)',
        'glow-cyan': 'var(--shadow-glow-primary-sm)',
        'glow-gold': '0 0 20px rgba(255, 215, 0, 0.3)',
        soft: 'var(--shadow-sm)',
        premium: 'var(--shadow-lg)',
      },

      /* ==========================================================================
         ANIMATIONS - Using design system tokens
         ========================================================================== */
      animation: {
        'neon-breath': 'glow-breath-primary 3s ease-in-out infinite',
        float: 'float 3s ease-in-out infinite',
        shimmer: 'shimmer 2s infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
      },
      keyframes: {
        'glow-breath-primary': {
          '0%, 100%': { boxShadow: 'var(--shadow-glow-primary-xs)' },
          '50%': { boxShadow: 'var(--shadow-glow-primary-md)' },
        },
        'glow-breath-secondary': {
          '0%, 100%': { boxShadow: 'var(--shadow-glow-secondary-xs)' },
          '50%': { boxShadow: 'var(--shadow-glow-secondary-md)' },
        },
        'glow-pulse': {
          '0%': { boxShadow: 'var(--shadow-glow-pulse-primary)' },
          '50%': { boxShadow: 'var(--shadow-glow-primary-lg)' },
          '100%': { boxShadow: 'var(--shadow-glow-pulse-primary)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(var(--space-4))' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },

      /* ==========================================================================
         BACKDROP BLUR - Enhanced blur effects
         ========================================================================== */
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        premium: '24px',
      },

      /* ==========================================================================
         CONTAINER SIZES - Responsive containers
         ========================================================================== */
      maxWidth: {
        'container-xs': 'var(--container-xs)',
        'container-sm': 'var(--container-sm)',
        'container-md': 'var(--container-md)',
        'container-lg': 'var(--container-lg)',
        'container-xl': 'var(--container-xl)',
        'container-2xl': 'var(--container-2xl)',
        'container-3xl': 'var(--container-3xl)',
        'container-4xl': 'var(--container-4xl)',
        'container-5xl': 'var(--container-5xl)',
        'container-6xl': 'var(--container-6xl)',
        'container-7xl': 'var(--container-7xl)',
      },

      /* ==========================================================================
         GRID TEMPLATES - Using design system tokens
         ========================================================================== */
      gridTemplateColumns: {
        'responsive-2': 'repeat(auto-fit, minmax(16rem, 1fr))',
        'responsive-3': 'repeat(auto-fit, minmax(20rem, 1fr))',
        'responsive-4': 'repeat(auto-fit, minmax(12rem, 1fr))',
      },
    },
  },
  plugins: [],
  safelist: [
    // Design system classes
    'text-display',
    'text-headline',
    'text-title',
    'text-subtitle',
    'text-body',
    'text-body-small',
    'text-caption',
    'text-label',
    'text-button',
    'text-code',
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-inverse',
    'text-success',
    'text-warning',
    'text-error',
    'text-info',
    'text-interactive',
    'text-interactive:hover',

    // Button classes
    'btn',
    'btn-primary',
    'btn-secondary',
    'btn-accent',
    'btn-success',
    'btn-warning',
    'btn-error',
    'btn-info',
    'btn-xs',
    'btn-sm',
    'btn-md',
    'btn-lg',
    'btn-xl',
    'btn-ghost',
    'btn-outline',
    'btn-loading',
    'btn-group',

    // Form classes
    'form',
    'form-section',
    'form-group',
    'form-row',
    'form-actions',
    'field',
    'field-horizontal',
    'label',
    'label-required',
    'input',
    'input-xs',
    'input-sm',
    'input-md',
    'input-lg',
    'input-xl',
    'input-success',
    'input-error',
    'input-warning',
    'textarea',
    'textarea-xs',
    'textarea-sm',
    'textarea-md',
    'textarea-lg',
    'textarea-xl',
    'select',
    'select-xs',
    'select-sm',
    'select-md',
    'select-lg',
    'select-xl',
    'checkbox',
    'radio',
    'help-text',
    'error-message',

    // Card classes
    'card',
    'glass-card',
    'card-xs',
    'card-sm',
    'card-md',
    'card-lg',
    'card-xl',
    'card-primary',
    'card-secondary',
    'card-success',
    'card-warning',
    'card-error',
    'card-info',
    'card-horizontal',
    'card-compact',
    'card-cyber',
    'card-header',
    'card-title',
    'card-subtitle',
    'card-content',
    'card-actions',

    // Layout classes
    'container',
    'container-xs',
    'container-sm',
    'container-md',
    'container-lg',
    'container-xl',
    'container-2xl',
    'container-3xl',
    'container-4xl',
    'container-5xl',
    'container-6xl',
    'container-7xl',
    'flex-col-mobile',
    'flex-col-tablet',
    'flex-col-desktop',
    'grid-responsive',
    'grid-responsive-2',
    'grid-responsive-3',
    'grid-responsive-4',
    'space-responsive-xs',
    'space-responsive-sm',
    'space-responsive-md',

    // Responsive visibility
    'sm-show',
    'md-show',
    'lg-show',
    'xl-show',
    'xl2-show',
    'sm-hide',
    'md-hide',
    'lg-hide',
    'xl-hide',
    'xl2-hide',

    // Shadow classes
    'shadow-glow-primary-xs',
    'shadow-glow-primary-sm',
    'shadow-glow-primary-md',
    'shadow-glow-primary-lg',
    'shadow-glow-secondary-xs',
    'shadow-glow-secondary-sm',
    'shadow-glow-secondary-md',
    'shadow-glow-secondary-lg',
    'shadow-glow-accent-xs',
    'shadow-glow-accent-sm',
    'shadow-glow-accent-md',
    'shadow-glow-accent-lg',
    'shadow-glass',
    'shadow-cyber-card',
    'shadow-interactive',
    'shadow-floating',
    'shadow-glow-breath-primary',
    'shadow-glow-breath-secondary',
    'shadow-glow-pulse',
    'shadow-lift',

    // Animation classes
    'animate-fade-in',
    'animate-slide-up',
    'animate-scale-in',
    'card-enter',
    'card-exit',

    // Legacy classes for backward compatibility
    'glass-card',
    'glass-card-cyan',
    'glass-card-magenta',
    'glass-card-gold',
    'btn-premium',
    'btn-magenta',
    'btn-cyan',
    'btn-gold',
    'input-premium',
    'toggle-premium',
    'text-glow-magenta',
    'text-glow-cyan',
    'text-glow-gold',
    'text-gradient-gold',
    'text-gradient-neon',
    'text-neon-magenta',
    'text-neon-cyan',
    'bg-neon-magenta',
    'bg-neon-cyan',
    'border-neon-magenta',
    'border-neon-cyan',
    'border-gold',
    'neon-breath',
    'shimmer',
    'float',
    'rounded-widget',
    'rounded-widget-sm',
    'rounded-widget-lg',
    'shadow-glow-magenta',
    'shadow-glow-cyan',
    'shadow-glow-gold',
    'shadow-neon-magenta',
    'shadow-neon-cyan',
    'bg-glass-light',
    'bg-glass-medium',
    'bg-glass-heavy',
  ],
};
