import jsPDF from 'jspdf';
import { Sprint, Pillar } from '../types';

export const generateTrophyPDF = (sprint: Sprint, pillars: Pillar[]) => {
  const doc = new jsPDF();

  // Colors (cyberpunk theme)
  const primaryColor = [255, 0, 255]; // Magenta
  const secondaryColor = [0, 255, 255]; // Cyan
  const accentColor = [255, 215, 0]; // Gold

  // Background gradient effect
  doc.setFillColor(20, 20, 20);
  doc.rect(0, 0, 210, 297, 'F');

  // Title with trophy emoji
  doc.setFontSize(28);
  doc.setTextColor(...primaryColor);
  doc.text('🏆 WEEKLY TROPHY 🏆', 105, 30, { align: 'center' });

  // Subtitle
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('Achievement Unlocked!', 105, 45, { align: 'center' });

  // Sprint Information Box
  doc.setFillColor(30, 30, 30);
  doc.rect(20, 55, 170, 25, 'F');
  doc.setDrawColor(...secondaryColor);
  doc.setLineWidth(1);
  doc.rect(20, 55, 170, 25);

  doc.setFontSize(14);
  doc.setTextColor(...secondaryColor);
  doc.text('SPRINT INFORMATION', 25, 68);

  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text(`Goal: ${sprint.goal}`, 25, 80);
  doc.text(`Week: ${sprint.week}/${sprint.year}`, 25, 90);

  // Statistics Section
  doc.setFillColor(30, 30, 30);
  doc.rect(20, 95, 170, 35, 'F');
  doc.setDrawColor(...accentColor);
  doc.rect(20, 95, 170, 35);

  doc.setFontSize(14);
  doc.setTextColor(...accentColor);
  doc.text('STATISTICS', 25, 108);

  const completedDays = sprint.progress.filter(d => d.checked).length;
  const totalTasks = sprint.done_tasks.length;
  const completionRate = sprint.progress.length > 0 ? Math.round((completedDays / sprint.progress.length) * 100) : 0;

  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(`📅 Days Completed: ${completedDays}/7 (${completionRate}%)`, 25, 120);
  doc.text(`✅ Tasks Done: ${totalTasks}`, 25, 130);
  doc.text(`🚧 Blocked Tasks: ${sprint.blocked_tasks.length}`, 25, 140);

  // Pillars Progress Section
  doc.setFillColor(30, 30, 30);
  doc.rect(20, 145, 170, 80, 'F');
  doc.setDrawColor(...primaryColor);
  doc.rect(20, 145, 170, 80);

  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.text('PILLARS PROGRESS', 25, 158);

  let yPos = 170;
  pillars.slice(0, 6).forEach((pillar, index) => { // Limit to 6 pillars for space
    const progressBar = '█'.repeat(Math.floor(pillar.completion / 10)) + '░'.repeat(10 - Math.floor(pillar.completion / 10));
    const statusEmoji = pillar.completion >= 90 ? '🔥' : pillar.completion >= 70 ? '📈' : pillar.completion >= 50 ? '⚡' : '🌱';

    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`${statusEmoji} ${pillar.name}`, 25, yPos);

    // Progress bar
    doc.setTextColor(...secondaryColor);
    doc.text(`[${progressBar}] ${pillar.completion}%`, 25, yPos + 6);

    yPos += 12;
  });

  // Achievement Title (based on performance)
  let achievementTitle = '';
  let achievementColor = primaryColor;

  if (completionRate >= 100 && totalTasks >= 5) {
    achievementTitle = '🏆 SPRINT LEGEND';
    achievementColor = accentColor;
  } else if (completionRate >= 85 && totalTasks >= 3) {
    achievementTitle = '🥇 SPRINT CHAMPION';
    achievementColor = accentColor;
  } else if (completionRate >= 70) {
    achievementTitle = '🥈 SPRINT WARRIOR';
    achievementColor = secondaryColor;
  } else if (completionRate >= 50) {
    achievementTitle = '🥉 SPRINT SURVIVOR';
    achievementColor = primaryColor;
  } else {
    achievementTitle = '💪 KEEP GOING';
    achievementColor = [255, 100, 100]; // Light red
  }

  doc.setFontSize(18);
  doc.setTextColor(...achievementColor);
  doc.text(achievementTitle, 105, 240, { align: 'center' });

  // Motivational Quote
  const quotes = [
    '"Success is not final, failure is not fatal: it is the courage to continue that counts."',
    '"The only way to do great work is to love what you do."',
    '"Believe you can and you\'re halfway there."',
    '"The future belongs to those who believe in the beauty of their dreams."',
    '"Keep going. Everything you need will come to you at the perfect time."'
  ];

  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];

  doc.setFontSize(10);
  doc.setTextColor(200, 200, 200);
  const splitQuote = doc.splitTextToSize(randomQuote, 150);
  doc.text(splitQuote, 105, 255, { align: 'center' });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by FlexGrafik Accountability OS', 105, 280, { align: 'center' });
  doc.text(`Created: ${new Date().toLocaleDateString('pl-PL')} ${new Date().toLocaleTimeString('pl-PL')}`, 105, 285, { align: 'center' });

  // Save the PDF
  const filename = `trophy-week-${sprint.week}-${sprint.year}.pdf`;
  doc.save(filename);

  return filename;
};

// Helper function to generate achievement titles based on performance
export const getAchievementTitle = (sprint: Sprint): string => {
  const completedDays = sprint.progress.filter(d => d.checked).length;
  const completionRate = sprint.progress.length > 0 ? (completedDays / sprint.progress.length) * 100 : 0;
  const totalTasks = sprint.done_tasks.length;

  if (completionRate >= 100 && totalTasks >= 5) return 'SPRINT LEGEND 🏆';
  if (completionRate >= 85 && totalTasks >= 3) return 'SPRINT CHAMPION 🥇';
  if (completionRate >= 70) return 'SPRINT WARRIOR 🥈';
  if (completionRate >= 50) return 'SPRINT SURVIVOR 🥉';
  return 'KEEP GOING 💪';
};